### ISSUE TITLE
link for downloading the meta files of laion-coco

### ISSUE THREAD

**Issue by wztxywww123** [LAION-AI/laion.ai#46]
Hi, thanks for your awesome work! 
I have downloaded the LAION-5B dataset and now I want to download the LAION-COCO. As far as I know, LAION-COCO is a sub set of LAION-5B. Can I just download the LAION-COCO‘s caption file to avoid repeated image downloads.

**Comment by rom1504** [comment]
https://laion.ai/blog/laion-coco/ you can find the data there

**Comment by wztxywww123** [comment]
Thanks for your reply. From this link, I can download the LAION-COCO dataset, but I need to download all the images. I already have the LAION-5B dataset, and the images in LAION-COCO are duplicates of those in LAION-5B. Can I only download the caption files of LAION-COCO?

**Comment by rom1504** [comment]
You could download the laion coco files and join with your already
downloaded images maybe. You'd have the write the code for the join though,
we don't have existing code for this

**Comment by wztxywww123** [comment]
Thanks
